# Generated by Django 5.2.1 on 2025-05-28 03:16

import core.utils.upload_img
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rider",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                (
                    "rider_img_body",
                    models.ImageField(upload_to=core.utils.upload_img.upload_img),
                ),
                (
                    "rider_img_sm",
                    models.ImageField(upload_to=core.utils.upload_img.upload_img),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                (
                    "year",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1800)]
                    ),
                ),
                ("synopsis", models.CharField(blank=True)),
                (
                    "show_img_xg",
                    models.ImageField(upload_to=core.utils.upload_img.upload_img),
                ),
                (
                    "show_img_sm",
                    models.ImageField(upload_to=core.utils.upload_img.upload_img),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiderForm",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.rider"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rider",
            name="tv_show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.show"
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=15, unique=True)),
                ("password", models.CharField()),
                ("img", models.ImageField(upload_to=core.utils.upload_img.upload_img)),
                (
                    "favorite_riders",
                    models.ManyToManyField(blank=True, to="core.rider"),
                ),
                ("favorite_shows", models.ManyToManyField(blank=True, to="core.show")),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField()),
                ("date", models.DateField()),
                ("img", models.ImageField(upload_to=core.utils.upload_img.upload_img)),
                (
                    "tagged_riders",
                    models.ManyToManyField(related_name="posts", to="core.rider"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_review", models.CharField(blank=True)),
                (
                    "fav_riders",
                    models.ManyToManyField(related_name="fav_shows", to="core.show"),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.show"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField()),
                ("date", models.DateField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.post"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.user",
                    ),
                ),
            ],
        ),
    ]
