# Generated by Django 5.2.1 on 2025-05-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="show_img_banner",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="show",
            name="show_img_logo",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="show",
            name="show_img_sm",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="show",
            name="show_img_xl",
            field=models.CharField(max_length=100),
        ),
    ]
