# Generated by Django 5.2.1 on 2025-07-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("show", "user"), name="unique_review_per_show_per_user"
            ),
        ),
    ]
