# Generated by Django 5.2.1 on 2025-06-01 03:10

import core.utils.upload_img
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_show_show_img_banner_alter_show_show_img_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="show",
            name="show_img_banner",
            field=models.ImageField(upload_to=core.utils.upload_img.upload_img),
        ),
        migrations.AlterField(
            model_name="show",
            name="show_img_logo",
            field=models.ImageField(upload_to=core.utils.upload_img.upload_img),
        ),
        migrations.AlterField(
            model_name="show",
            name="show_img_sm",
            field=models.ImageField(upload_to=core.utils.upload_img.upload_img),
        ),
        migrations.AlterField(
            model_name="show",
            name="show_img_xl",
            field=models.ImageField(upload_to=core.utils.upload_img.upload_img),
        ),
    ]
