# Generated by Django 5.2.1 on 2025-05-23 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_img_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800)])),
                ('synopsis', models.CharField(blank=True)),
                ('show_img_xg', models.ImageField(upload_to='media/shows/posters/<django.db.models.fields.CharField>')),
                ('show_img_sm', models.ImageField(upload_to='media/shows/icons/<django.db.models.fields.CharField>_sm')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(upload_to='media/users'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_shows',
            field=models.ManyToManyField(to='core.show'),
        ),
    ]
