# Generated by Django 5.2.1 on 2025-05-23 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_show_alter_user_img_user_favorite_shows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('rider_img_body', models.ImageField(upload_to='', verbose_name='/media/riders/<django.db.models.fields.CharField>_<django.db.models.fields.AutoField>_xg')),
                ('rider_img_sm', models.ImageField(upload_to='', verbose_name='/media/riders/<django.db.models.fields.CharField>_<django.db.models.fields.AutoField>_sm')),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.show')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_riders',
            field=models.ManyToManyField(to='core.rider'),
        ),
        migrations.CreateModel(
            name='RiderForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rider')),
            ],
        ),
    ]
