# Generated by Django 5.2.1 on 2025-06-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_user_favorite_riders_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
