# Generated by Django 5.2.1 on 2025-05-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_riders',
            field=models.ManyToManyField(blank=True, to='core.rider'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_shows',
            field=models.ManyToManyField(blank=True, to='core.show'),
        ),
    ]
