# Generated by Django 5.2.1 on 2025-05-23 21:08

import core.models.show
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_favorite_riders_alter_user_favorite_shows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_img_sm',
            field=models.ImageField(upload_to=core.models.show.upload_show_icon),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_img_xg',
            field=models.ImageField(upload_to=core.models.show.upload_show_poster),
        ),
    ]
