# Generated by Django 5.2.1 on 2025-05-23 21:21

import core.models.rider
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_show_show_img_sm_alter_show_show_img_xg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='rider_img_body',
            field=models.ImageField(upload_to=core.models.rider.upload_rider_body),
        ),
        migrations.AlterField(
            model_name='rider',
            name='rider_img_sm',
            field=models.ImageField(upload_to=core.models.rider.upload_rider_icon),
        ),
    ]
