# Generated by Django 5.2.1 on 2025-05-23 21:37

import core.models.post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_rider_rider_img_body_alter_rider_rider_img_sm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to=core.models.post.upload_post_img),
        ),
    ]
